tests: Fix a type mismatch in libdnf5-cli/test_progressbar
Building tests on i686 architecture failed like this:

    In file included from /usr/include/cppunit/TestCase.h:6,
		     from /builddir/build/BUILD/dnf5-5.4.0.0-build/dnf5-5.4.0.0/test/libdnf5-cli/test_progressbar.hpp:24,
		     from /builddir/build/BUILD/dnf5-5.4.0.0-build/dnf5-5.4.0.0/test/libdnf5-cli/test_progressbar.cpp:21:
    /builddir/build/BUILD/dnf5-5.4.0.0-build/dnf5-5.4.0.0/test/libdnf5-cli/test_progressbar.cpp: In member function ‘void ProgressbarTest::test_progress_bar_multi_byte_character()’:
    /builddir/build/BUILD/dnf5-5.4.0.0-build/dnf5-5.4.0.0/test/libdnf5-cli/test_progressbar.cpp:55:5: error: no matching function for call to ‘assertEquals(long unsigned int&, unsigned int&, CppUnit::SourceLine, const char [1])’
       55 |     CPPUNIT_ASSERT_EQUAL(expected, num_lines);
	  |     ^
      • there is 1 candidate
	• candidate 1: ‘template<class T> void CppUnit::assertEquals(const T&, const T&, SourceLine, const std::string&)’
	  /usr/include/cppunit/TestAssert.h:161:6:
	    161 | void assertEquals( const T& expected,
		|      ^~~~~~~~~~~~
	  • template argument deduction/substitution failed:
	    •   deduced conflicting types for parameter ‘const T’ (‘long unsigned int’ and ‘unsigned int’)
	      /builddir/build/BUILD/dnf5-5.4.0.0-build/dnf5-5.4.0.0/test/libdnf5-cli/test_progressbar.cpp:55:5:
		 55 |     CPPUNIT_ASSERT_EQUAL(expected, num_lines);
		    |     ^

The cause was a comparison between two variables of different types,
size_t and unsigned long int, that have a different rank on 32-bit
platforms, leading to a template argument mismatch.

This flaw was introduced in commit
7b137b9148ec9f025162bbfe817de1a32830fc3d ("libdnf5-cli: handle C or
POSIX locale gracefully in progressbar width calculation").

This patch fixes it.

https://bugzilla.redhat.com/show_bug.cgi?id=2443774