Workaround for swig-4.2.0 missing fragment dependency
Fixes error:
repoPYTHON_wrap.cxx:5656:56: error: expected template-name before '<' token
 5656 |     struct SwigPyMapIterator_T : SwigPyIteratorClosed_T<OutIterator, ValueType, FromOper>

due to missing SWIG %fragment dependency on SwigPyIterator_T which provides the missing base class SwigPyIteratorClosed_T.

See https://github.com/swig/swig/issues/2744