test: ease path assertions in tests
Building dnf5 with Arch Linux's build tooling fails as an absolute path
is recorded instead of an absolute path:

AssertionError: "^libdnf5/logger/global_logger.cpp:[0-9]+:
libdnf5::GlobalLogger::GlobalLogger\(\): API Assertion 'librepo_logger
== nullptr' failed: Only one GlobalLogger can exist at a time" does not
match
"/usr/src/debug/dnf5/dnf5-5.2.13.0/libdnf5/logger/global_logger.cpp:33:
libdnf5::GlobalLogger::GlobalLogger(): API Assertion 'librepo_logger ==
nullptr' failed: Only one GlobalLogger can exist at a time"

Closes: #2250