Define FNM_EXTMATCH for musl
Fixes the following compilation errors with musl that does not have
FNM_EXTMATCH defined:
```
error: 'FNM_EXTMATCH' undeclared (first use in this
function); did you mean 'FNM_NOMATCH'?
```

Signed-off-by: Adam Duskett <adam.duskett@amarulasolutions.com>