Fix: Do not use Variable-length arrays (VLAs) in C++ code
Variable Length Arrays (VLAs) are supported in C (since the C99 standard).
But not in the C++ standard. This is an extension of some compilers.

Fixes:
error: variable length arrays in C++ are a Clang extension