Require rpm>=4.19.0 for sysusers, {pre,post}untrans RPM tags
083570d3cc7c added support for sysusers and {pre,post}untrans scriptlets.
Relevant RPM tags were introduced in RPM 4.19.0 but since CMake is satisfied
with RPM as old as 4.17.0, it leads to build failures:

	-- Checking for module 'rpm>=4.17.0'
	--   Found rpm, version 4.18.1
	-- Looking for rpmteSetVfyLevel in rpm
	-- Looking for rpmteSetVfyLevel in rpm - not found
	(...)
	-- Checking for module 'rpm'
	--   Found rpm, version 4.18.1
	(...)
	-- Checking for module 'rpm>=4.17.0'
	--   Found rpm, version 4.18.1
	(...)
	/home/rpm/rpmbuild/BUILD/libdnf5/rpm/transaction.cpp: In static member function 'static libdnf5::rpm::TransactionCallbacks::ScriptType libdnf5::rpm::Transaction::rpm_tag_to_script_type(rpmTag_e)':
	/home/rpm/rpmbuild/BUILD/libdnf5/rpm/transaction.cpp:489:14: error: 'RPMTAG_SYSUSERS' was not declared in this scope; did you mean 'RPMTAG_FSSIZES'?
	  489 |         case RPMTAG_SYSUSERS:
	      |              ^~~~~~~~~~~~~~~
	      |              RPMTAG_FSSIZES
	/home/rpm/rpmbuild/BUILD/libdnf5/rpm/transaction.cpp:491:14: error: 'RPMTAG_PREUNTRANS' was not declared in this scope; did you mean 'RPMTAG_PRETRANS'?
	  491 |         case RPMTAG_PREUNTRANS:
	      |              ^~~~~~~~~~~~~~~~~
	      |              RPMTAG_PRETRANS
	/home/rpm/rpmbuild/BUILD/libdnf5/rpm/transaction.cpp:493:14: error: 'RPMTAG_POSTUNTRANS' was not declared in this scope; did you mean 'RPMTAG_POSTTRANS'?
	  493 |         case RPMTAG_POSTUNTRANS:
	      |              ^~~~~~~~~~~~~~~~~~
	      |              RPMTAG_POSTTRANS

Fixes: #2169