reposync: Prevent a --min-buildtime overflow on 32-bit platforms
Compilation on i686 failed:

    /builddir/build/BUILD/dnf5-5.4.3.0-build/dnf5-5.4.3.0/dnf5-plugins/reposync_plugin/reposync.cpp: In member function ‘dnf5::ReposyncCommand::download_list_type dnf5::ReposyncCommand::get_packages_list(const libdnf5::repo::Repo&)’:
    /builddir/build/BUILD/dnf5-5.4.3.0-build/dnf5-5.4.3.0/dnf5-plugins/reposync_plugin/reposync.cpp:247:60: error: conversion from ‘int64_t’ {aka ‘long long int’} to ‘time_t’ {aka ‘long int’} may change value [-Werror=conversion]
      247 |         query.filter_recent(min_buildtime_option->get_value());
	  |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~

The cause was a disagreement between
libdnf5::cli::session::DateOption::get_value() type (int64_t) and
PackageQuery::filter_recent() type (time_t).

This quick fix was choosen becaue it does not changes API in any way.

Ideal fix would be either changing
libdnf5::cli::session::DateOption::get_value() type or adding yet another
PackageQuery::filter_recent() accepting int64_t. (We could make a template, but
would not have to forget on adding few instances into language bindings.)

Less deal fix would be adding libdnf5::cli::session::DateOption::get_value()
which returns time_t, so tthat we can stop usning type casts through out the
code.