dnf5-plugin automatic: Fix missing virtual destructor in dnf5::Emmiter
Fixes multiple compilation errors. Examples:

error: delete called on 'dnf5::Emitter' that is abstract but has
non-virtual destructor

error: delete called on non-final 'dnf5::EmitterStdIO' that has virtual
functions but non-virtual destructor