exception: Add new error for incorrect API usages
Introducing a new `UserAssertionError` to be thrown when clients are using our public API in a bad way.

This one is intended to be handled on the SWIG layer as opposed to the `AssertionError` which is supposed to terminate the process and collect coredump.