Fix integer overflow on 32-bit platforms in D-Bus history limit
Building on i686 failed:

    /builddir/build/BUILD/dnf5-5.4.3.0-build/dnf5-5.4.3.0/dnf5daemon-server/services/history/history.cpp: In member function ‘sdbus::MethodReply History::list(sdbus::MethodCall&)’:
    /builddir/build/BUILD/dnf5-5.4.3.0-build/dnf5-5.4.3.0/dnf5daemon-server/services/history/history.cpp:414:51: error: conversion from ‘long long int’ to ‘__gnu_cxx::__normal_iterator<libdnf5::transaction::Transaction*, std::vector<libdnf5::transaction::Transaction> >::difference_type’ {aka ‘int’} may change value [-Werror=conversion]
      414 |         transactions.erase(transactions.begin() + limit, transactions.end());
	  |                                                   ^~~~~

The cause was right-hand side of "+" operator after an iterator requires a
ptrdiff_t type, which is 32-bit signed int on 32-bit platforms. Hence the
compiler correctly complained that a limit value larger than 2^31-1 could be
misinterpreted when coercing 64-bit signed limit variable.

This patch adds thetype cast to placate the compiler and the necessary check
for the maximal representiable value for ptrdiff_t. It also adds a missing
uppper bound check for size_t type.