Fix: implicit conversion changes signedness, unused value
Fixes clang compilation errors:
4 x error: implicit conversion changes signedness
1 x error: variable 'total_bytes_read' set but not used