Add missing cast to fix build on i386
From: https://download.copr.fedorainfracloud.org/results/rpmsoftwaremanagement/dnf5-unstable/fedora-37-i386/06330258-dnf5/builder-live.log.gz
```
/builddir/build/BUILD/dnf5-5.1.2-20230822004434.9.g54ab9891/include/libdnf5-cli/output/repo_info.hpp:67:86: error: conversion from 'long long int' to 'time_t' {aka 'long int'} may change value [-Werror=conversion]
   67 |         last_update = fmt::format("{:%F %X}", std::chrono::system_clock::from_time_t(cache_updated));
      |                                                                                      ^~~~~~~~~~~~~
```