Fix compilation of python bindings
There are some redundant declarations present in python header files,
resulting in compilation warnings, e.g.:

In file included from /usr/include/python3.11/Python.h:91,
                 from /builddir/build/BUILD/dnf5-git-1850.2d6bfb8/redhat-linux-build/bindings/python3/libdnf5/CMakeFiles/python3_base.dir/basePYTHON_wrap.cxx:169:
/usr/include/python3.11/modsupport.h:37:24: error: redundant redeclaration of 'PyObject* _Py_BuildValue_SizeT(const char*, ...)' in same scope [-Werror=redundant-decls]
   37 | PyAPI_FUNC(PyObject *) _Py_BuildValue_SizeT(const char *, ...);
      |                        ^~~~~~~~~~~~~~~~~~~~
/usr/include/python3.11/modsupport.h:20:41: note: previous declaration of 'PyObject* _Py_BuildValue_SizeT(const char*, ...)'
   20 | #define Py_BuildValue                   _Py_BuildValue_SizeT
      |                                         ^~~~~~~~~~~~~~~~~~~~
/usr/include/python3.11/modsupport.h:36:24: note: in expansion of macro 'Py_BuildValue'
   36 | PyAPI_FUNC(PyObject *) Py_BuildValue(const char *, ...);
      |                        ^~~~~~~~~~~~~
In file included from /usr/include/python3.11/Python.h:100:

It needs to be fixed on Python side, we can only switch the warnings
off.